### ISSUE TITLE
Unable to broadcast transaction when user generates new address more than the threshold 

### ISSUE THREAD

**Issue by sunidhi64** [thunderbiscuit/padawan-wallet#122]
When user clicks on generate new address bunch of times, bdk-jni does not tells electrum server for these UTXOs
This issue will be resolved with bdk-jni new release where stop-gag variable can be set.
Reference: https://github.com/bitcoindevkit/bdk/issues/390

**Comment by thunderbiscuit** [comment]
This has now been fixed!
