### ISSUE TITLE
Use slider to choose fees

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#125]
I think this might also be a good first element to try and build using Compose.

**Comment by masterchief164** [comment]
I'd like to work on this issue.

**Comment by thunderbiscuit** [comment]
Sounds good!

To answer your question about the range, I think something like 1 to 20 would be good? There is nothing really limiting the actual fee rate to a specific maximum, but in practice you'd very very rarely see more than 20. A common way to deal with this for mobile wallets is to have a simple slider or something easy to use, and some button "set custom fee rate" which offers you the full range of possibilities. Let's start with just a straight slider.

Also of note, this part of the wallet is still being developed in Compose, so this issue is not ready for tackling just yet. I _hope_ it can be ready in the next month or so, but I don't have a clear timeline. Most of the compose screens are up and running, but the core wallet functionality is still being ported over with the new UI.

**Comment by thunderbiscuit** [comment]
Just to be clear @masterchief164 don't put too much effort into this just yet because our Compose screen(s) for the wallet aren't yet developed.
