### ISSUE TITLE
Sync wallet on startup

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#127]

**Comment by sunidhi64** [comment]
I can work on it!

**Comment by darkvoid32** [comment]
Would a simple solution to this be calling : 
        _viewModel.updateBalance()
        viewModel.syncTransactionHistory()_
in the _onCreateView()_? Since I'm not sure if there might be side effects to this.

**Comment by thunderbiscuit** [comment]
I think this would work, the only thing is that it might be nice to have it done in the background in case it's a bigger wallet and the sync takes a few second, which I think will hang up the creation of the view.

We could try and do it first thing inside the `onViewCreated`, moving the code to sync used in the button to a method and just using that outright on the view creation and on the sync button onclicklistener?

**Comment by darkvoid32** [comment]
Good point on the bigger wallet issue since I'm not sure how long it will take on those bigger wallets. I think I can play around to see if it can be done in the background but if not I can just run sync in the onViewCreated.

**Comment by thunderbiscuit** [comment]
Just to give you an idea, a wallet with maybe 5-100 transactions will take 2 to 5 seconds to sync I would think. So nothing major, but also not really a 5 seconds you want your screen to be blank. So yeah feel free to experiment and see how it goes!
