### ISSUE TITLE
Test new logos

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#142]
The logo used for the app in the phone's launcher and on the app store is not optimal. The logo is not easy to make out. I'm speaking with a designer to explore these ideas:

1. thickening the lines of the logo
2. showing only half the face of character

**Comment by enyipreshious** [comment]
Hello @thunderbiscuit, Good job on the work you're doing with padawan. 

Is this issue something I can still try my hands on? I see the date of this issue has been long. 

I applied for the summer of bitcoin, design track and noted down improvement that could be made. The logo—which is this issue—being one of them.

**Comment by thunderbiscuit** [comment]
Yes absolutely! If you want a better sense for what I think the "problem" sort of is, download the app on the Play Store. You'll see the icon for the app is not super easy to make out. I'm not exactly sure what I'm looking for... just something better and more identifiable, yet keeping the spirit of the logo. Feel free to ask me any questions here or on the Discord server!

**Comment by thunderbiscuit** [comment]
Thanks @enyipreshious for the awesome new logo!
