### ISSUE TITLE
Add introduction tour of the app on first startup

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#146]
@sunidhi64 is working on this, see #143.

**Comment by janhaviiii** [comment]
Can I work on this issue @thunderbiscuit ?

**Comment by thunderbiscuit** [comment]
This issue is currently in "standby", because I'm rewriting the UI in Jetpack Compose. This will change most of how we think/implement the UI, and so from there we'll see where we go. But for now I don't think it's worth spending time/resources on this.

**Comment by janhaviiii** [comment]
Okay sir, understood. Thank you so much.

**Comment by PK284** [comment]
Is this issue still open?

**Comment by thunderbiscuit** [comment]
Yes it is! Not sure yet how to best go about this, so feel free to propose ideas and libraries before putting too much time into a PR. This is potentially a big change, so I'm not yet sure how to it will shake out. Happy to bounce ideas around first.
