### ISSUE TITLE
Summer of Bitcoin Project Template: Extend Devkit Wallet with more advanced Bitcoindevkit APIs

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#149]
**Description**
The [Devkit Wallet](https://github.com/thunderbiscuit/devkit-wallet) is the reference sample app for the [bdk-android](https://github.com/bitcoindevkit/bdk-kotlin) library. It's an Android native app written in Kotlin, whose goal is to demonstrate how to leverage the bitcoindevkit on Android.

**Expected Outcomes**
The wallet currently only has 2 active "branches": a UI-only branch and a simple wallet branch. The simple wallet branch implements the basic functionalities of a mobile wallet. This project would create a new branch which would implement a range of more advanced features of bitcoin wallets, including adding block data options, UTXO selection, RBF, and much more. Full documentation on how to build the advanced branch of the wallet is expected in the form of a new page on the companion tutorial website.

**Resources**
The [companion website](https://thunderbiscuit.github.io/devkit-wallet/) for the app is a good starting point, since it describes well both current branches.

**Skills Required**
Some knowledge of Android is important, but the wallet is not heavy on Android specifics. Knowledge of (or keen interest in) Kotlin is the most important part of the requirements.

**Difficulty**
Hard.

**Comment by skdbsp123** [comment]
Hey @thunderbiscuit 
I am Satyam, and for the upcoming Summer of Bitcoin, I wish to contribute to this project. 
I have good experience of working with android, two years using Java and 6 months using Kotlin. I have interned at Atom EI, their app is live on Play Store with more than 500K downloads and 5 star rating with more than 25k ratings. I mostly worked with kotlin. I am attaching my resume for your reference here: [resume](https://drive.google.com/file/d/1INjHH4ErQroJr65ClFN-sZdiEJs6SCnM/view?usp=sharing) 

I have started reading about the project and will soon dive into the codebase. 

Please let me know if there are any prerequisites for the project. It would also help me if you could give some advice or instructions to follow for better understanding of the project as well as the codebase.

Looking forward to a great summer ahead.

**Comment by thunderbiscuit** [comment]
Sounds good! Feel free to open issues and ask questions on the repo for the Devkit Wallet.

Let me know if the app compiles and runs well on your machine. Take a look at the companion website, which should get you started. It think it might be in need of a few fixes too, so if you end up looking into it, feel free to open a PR if you see discrepancies between the app and the docs website. Cheers!

**Comment by skdbsp123** [comment]
Hey @thunderbiscuit , App compiled and runs fine on my device. There are certain issues, UI to be in particular, as certain importat components like buttons are not at their correct positions. I shall try to fix these small issues first.

I shall let you now of the progress. If you want any particular task to be completed or bug to be fixed, let me know.

**Comment by thunderbiscuit** [comment]
Sounds good! The only thing I would say is I'm trying to migrate the UI to Compose, so if you see easy and quick fixes feel free to PR them, but don't waste too much time on UI just yet, because hopefully all of that is gone soon enough...

**Comment by thunderbiscuit** [comment]
@skdbsp123 unfortunately I'll be removing this as a Summer of Bitcoin project. But very similar to this one is the Padawan project proposal #150. It's using the same library, and a lot of things are the same! In fact some of the advancements in Padawan could easily be ported back to the Devkit Wallet.
