### ISSUE TITLE
Summer of Bitcoin Project Proposal: Work on developing bdk-python

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#151]
## Description
The Bitcoindevkit is using language bindings to offer packages and libraries in different languages. [bdk-python](https://github.com/thunderbiscuit/bdk-python) is fairly new (December 2021), but shows great promise. We are looking for someone knowledgeable with Python to help develop the package into a more mature [package on PyPI](https://pypi.org/project/bdkpython/).

The student would be working with the team to further the goals of the bitcoindevkit and make meaningful progress towards the expected outcomes defined in the next section.

## Expected Outcomes
Develop the test suite, enable automatic deployment using GitHub Actions, writing of small example applications leveraging the library, blog posts, and documentation. This project is for someone interested in bringing the library to a more mature state on PyPI, and working alongside the bdk-kotlin and bdk-swift libraries to ensure consistent APIs and code coverage.

## Resources
The bitcoindevkit project currently maintains four language bindings libraries: [bdk-jvm](https://github.com/bitcoindevkit/bdk-kotlin), [bdk-android](https://github.com/bitcoindevkit/bdk-kotlin), [bdk-swift](https://github.com/bitcoindevkit/bdk-swift), and [bdk-python](https://github.com/thunderbiscuit/bdk-python). There is good working knowledge of how those bindings work within the team.

## Skills Required
Good working knowledge of Python.

## Difficulty
Medium.

**Comment by GoutamVerma** [comment]
Hello @thunderbiscuit,
I'm Goutam from India, an upcoming contributor at Summer of Bitcoin 22,  A full-stack developer working with tech stacks like Android, python, and Networking. I have contributed to many Opensource organizations and Tech Education Teams in the past years. I also have a good knowledge of designing GitHub actions and writing test-cases for android applications.

I read out all documentation and information regarding the bdk-python and bdk-java and have good examples for designing test cases. And completely got the outcomes expected from contributors. 

I want to know more about actions.

**Comment by thunderbiscuit** [comment]
I'll close this issue as it was moved to the [bdk-ffi](https://github.com/bitcoindevkit/bdk-ffi/issues/102) repository.

**Comment by thunderbiscuit** [comment]
Hi @GoutamVerma! Welcome to the bitcoindevkit. Feel free to comment on the issue under the new repo (bdk-ffi). 

You say you want to know more about actions? I'm not sure what you mean by that. If you're getting started with the repos and the language bindings, feel free to let us know if you run into trouble or you want clarifications on different things.

Cheers!
