### ISSUE TITLE
Send transaction dialog doesn't show correct total fees

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#152]

**Comment by divyank00** [comment]
Any screenshot for this issue?

**Comment by thunderbiscuit** [comment]
Yep. So what is happening is that the Dialog is showing the fee rate whereas we'd like it to show the total fees (in satoshis), or maybe the total fees + the fee rate in stats per vbyte.

![screenshot0](https://user-images.githubusercontent.com/39974688/151667489-eda37c11-3df3-4b30-9559-3e718193750e.png)

![screenshot1](https://user-images.githubusercontent.com/39974688/151667525-49736bf1-6ba8-4243-b478-023793aec282.png)
