### ISSUE TITLE
Add confirmation message

### ISSUE THREAD

**Issue by dhruv-1001** [thunderbiscuit/padawan-wallet#160]
No confirmation message is shown on clicking "copy" TextView on Send Coins Back screen (`SendCoinsBackFragment.kt`). 
This might confuse users as no message confirms that they have successfully copied the address.

Screenshot for mentioned screen - 
![Padawan_issue_image](https://user-images.githubusercontent.com/55213645/156413117-7e987c10-3173-49ea-808f-0148cca5aa2c.jpeg)

**Comment by thunderbiscuit** [comment]
Good point. Thanks for adding the issue!

**Comment by dhruv-1001** [comment]
I'll take on this issue.
How should I handle this, through a toast?

**Comment by thunderbiscuit** [comment]
No I'm trying to remove reliance on toasts as they are deprecated. Snackbars is what I want to start using, but note that I had a hard time making it work previously for the "receive" tab. See #50. So not exactly sure how to make it work, but I imagine it should be not too hard.

**Comment by darkvoid32** [comment]
You can look at #161 for my solution for adding snackbars

**Comment by dhruv-1001** [comment]
Issue solved.
