### ISSUE TITLE
Automatically Synchronize the wallet on startup.

### ISSUE THREAD

**Issue by masterchief164** [thunderbiscuit/padawan-wallet#185]

**Comment by darkvoid32** [comment]
The wallet should be syncing on startup automatically, which can be seen from the snackbar that pops up on launch. Does it not work on your phone?

**Comment by masterchief164** [comment]
I guess it was fixed recently. I checked it before that and opened the issue, sorry for that.

**Comment by darkvoid32** [comment]
All good 👍
