### ISSUE TITLE
Add checks for services that are required during startup

### ISSUE THREAD

**Issue by masterchief164** [thunderbiscuit/padawan-wallet#192]
The app crashes if the app isn't connected to the internet while starting up. Moreover, if the wifi or the cellular connection doesn't allow the app to connect to the server the app just gets stuck and shows App Not Responding. This should be fixed.

**Comment by thunderbiscuit** [comment]
Good catch. I do think this is a problem we'll need to fix on the `bdk-ffi` side of things. I've opened an issue [here](https://github.com/bitcoindevkit/bdk-ffi/issues/135).

**Comment by thunderbiscuit** [comment]
Done.
