### ISSUE TITLE
Wallet sync doesn't check for network connection

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#194]
I believe this is a regression introduced in #165.

The `sync` button uses this code to sync:
```kotlin
        binding.syncButton.setOnClickListener {
            when (isNetworkAvailable(requireContext())) {
                true -> {
                    viewLifecycleOwner.lifecycleScope.launch(Dispatchers.IO) {
                        syncWallet()
                    }
                }
                false -> fireSnackbar(requireView(), SnackbarLevel.WARNING, "Network connection currently not available")
            }
        }
```

But the `onCreateView` calls the sync coroutine directly, without checking for network availability first:
```kotlin
        viewLifecycleOwner.lifecycleScope.launch(Dispatchers.IO) {
            syncWallet()
        }
```

**Comment by thunderbiscuit** [comment]
I can't quite reproduce it because of the bug described in #192, but I noticed it while investigating that issue. Opening this just to keep track of it.

**Comment by masterchief164** [comment]
Try opening the app with both wifi and cellular data turned off

**Comment by thunderbiscuit** [comment]
Yeah I'm able to make it crash, but I think it's because of the issue in 192, not because of this one here I don't think (attempting the sync without network access). For example you can try adding the check for network to the initial sync when `onCreateView` gets called, but the app will crash with the same error.
