### ISSUE TITLE
App doesn't open unless connected to the Internet

### ISSUE THREAD

**Issue by enyipreshious** [thunderbiscuit/padawan-wallet#208]
Padawan crushes if you try to open up the app without an internet connection

**To reproduce this behaviour:**
1. Switch off your mobile data
2. Click the app icon 
3. App crashes 

A suggestion I think can make the experience better will be to give the user some form of error message on why the app can't open. 

To make sure this wasn't only from my end. I tried it on another android phone(both android 11) and it gave the same result

**Comment by enyipreshious** [comment]
Padawan crushes if you try to open up the app without an internet connection

**To reproduce this behaviour:**
1. Switch off your mobile data
2. Click the app icon 
3. App crashes 


A suggestion that I expect will work would be to give the user some form of message/update on why the app can't open. 

To make sure this wasn't only from my end. I tried it on another android phone(both android 11) and it gave the same result

**Comment by darkvoid32** [comment]
Good find, Ill work on the fix

**Comment by thunderbiscuit** [comment]
Yep good issue to point out! I'll add it to the [milestone for the next release](https://github.com/thunderbiscuit/padawan-wallet/milestone/6).

@darkvoid32 this issue will have a different fix depending on the bdk-android version we use; we should upgrade to bdk-android 0.6.0 first and fix from there (the API for bdk has changed a lot and we have decoupled the wallet and blockchain constructs, meaning you can now create a wallet without syncing whereas before you needed an initial ping to the Electrum server before creating the wallet (as outlined [here](https://github.com/thunderbiscuit/padawan-wallet/issues/192) and [here on bdk-ffi](https://github.com/bitcoindevkit/bdk-ffi/issues/135).

**Comment by darkvoid32** [comment]
Related issues #194 , #192 .
We will wait for the next BDK-ffi release for new wallet implementation to tackle this issue

**Comment by thunderbiscuit** [comment]
Finally done!
