### ISSUE TITLE
Add "send all" feature

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#219]
Our current "send all" functionality simply pulls the wallet balance and displays it to the user, but the amount being sent is always a bit lower because the fees need to be pulled from this balance. It would be better if we could compute the actual sendable amount once a transaction has been pre-built and fees are correctly estimated.

**Comment by darkvoid32** [comment]
This should be on hold since we currently are unable to calculate the total fees spent. We should be able to do it if the transactions field in the TransactionDetail object is exposed to us.
