### ISSUE TITLE
Sending Bitcoin Page 

### ISSUE THREAD

**Issue by autumndomingo** [thunderbiscuit/padawan-wallet#221]
The main thing that became apparent during the research process was that users were confused about what to input into the "fee rate" box. The simple solution would be to add an example like "e.g. 2 or 10".

Another small feature that can be added is an icon that when pressed will have a pop up window that has a sentence explaining what a fee rate is and why they are important. This will help the user understand what that input means and continues to educate them outside of the tutorials.

![Screenshot (5)](https://user-images.githubusercontent.com/105660328/182931966-68f866db-c705-4061-b451-8287b289145e.png)

**Comment by thunderbiscuit** [comment]
I like the idea of the info icon! I think there are many such little buttons/wordings that could use a quick "tip" to explain to the user what they are, without always being a big deal and a full tutorial. This is a great idea.

For the fee rate itself, we've been thinking about removing the custom choice by default, and simply having a drop-down where the user would choose between a few options. Here is @enyipreshious's wireframe for it, let me know what you think:

![image](https://user-images.githubusercontent.com/39974688/183131170-7b36fa53-b9d4-46fb-a0c7-b7678a22fafe.png)

**Comment by autumndomingo** [comment]
I think that's a really cool concept. People might not understand what slow, normal, and fast means when it comes to bitcoin fee rates, so that is where the info icon can come into play as well.
