### ISSUE TITLE
Congratulation pop up on home page

### ISSUE THREAD

**Issue by autumndomingo** [thunderbiscuit/padawan-wallet#222]
After a transaction is completed, a little pop up window should come up that just says "Transaction Successful!". In addition, some animated confetti would be on the message. I drew a rough picture of what this could look like. By adding this feature will take away the doubt that the user has about the trasaction going through. When a transaction is complete it will automattically take the user from the "Sending Bitcoin" page, to the home screen which is where this pop up window will show up. 

![IMG_4368](https://user-images.githubusercontent.com/105660328/183122897-d1f1f470-ecc0-4a7d-b7ed-e98c749de41b.JPG)

**Comment by thunderbiscuit** [comment]
Pinging @enyipreshious and @Himanshu-523 on this!

I think we'll definitely need to add interactions once the transaction has been broadcast. I think @Himanshu-523 had some modals ready for that sort of thing.

**Comment by Ankit62042** [comment]
@thunderbiscuit is this still issue still open?I want to work on this issue

**Comment by thunderbiscuit** [comment]
Hi @Ankit62042! I'm not sure exactly how I want to handle this one yet. It requires a small re-thinking of the way I handle manual and automatic syncs, and I'm not sure it's something we can offer out of the box without changing more of the internals than I want to. 

I'm currently working on polishing the app for the 1.0 release. You can see the issues tagged for that [here](https://github.com/thunderbiscuit/padawan-wallet/issues?q=is%3Aopen+is%3Aissue+milestone%3Av1.0.0). One if you're interested, download the latest version of the app on the Play Store (0.10.0) and see if you can find bugs! Feel free to open issues with screenshots too if the app doesn't look as intended on your device.
