### ISSUE TITLE
Small additions to different parts of the app

### ISSUE THREAD

**Issue by autumndomingo** [thunderbiscuit/padawan-wallet#223]
Tutorial Page:
1. **Add a complete button at the end of each tutorial.** This will help with two things. The first is that it allows the user to feel a sense of completion when finishing a tutorial, which will encourage them to continue to keep learning. And the second reason is that it makes the ux a bit easier. It allows the user to exit the tutorial without much hassle, and return to the list of tutorials. 
2. **Have back arrows at the top left corner of the individual tutorial pages** so that if the user doesn't want to complete that tutorial they have an easy and clear way to return to the tutorial list.  Having an arrow on any page will help the user easily exit what page they're on with minimal confusion.  An example of this was in one of the interviews I conducted. The user opened up the "send bitcoin" page but she didn't want to send a transaction just yet. She wanted to go back but didn't know how. It took her a few seconds to figure out how to go back. If there was a simple back arrow she wouldn't have run into that problem. 
3. **Make the tutorials more concise, add diagrams or gifs, and add exercises that the user can complete.** During the interviews, users said that the tutorials were good and had helpful information, but there was a little too much information. By adding more visuals and interactions, the users will be more engaged and have more fun with the app.

**Comment by thunderbiscuit** [comment]
Love these!

I'm getting a copywriter to help me edit and simplify the tutorials, so I do agree that this is key. Even if in the end we have a few more tutorials, it's good to keep them simple and short, focused on teaching you one thing at a time.

The completion buttons and the arrow back buttons are for sure required! I think the guys are working them in the Figma files at the moment but I should double check.

**Comment by thunderbiscuit** [comment]
I think we did most of those! The last thing is to add images/gifs/diagrams to the tutorials, and I'll open individual issues for those. Closing this now!
