### ISSUE TITLE
Send screen to camera screen transition is awkward

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#233]
The send screen escapes down while the camera comes from below, and the reverse happens when you cancel or succeed on the QR code scan.

**Comment by ShreyParikh1002** [comment]
Hey @thunderbiscuit , Shrey this side, I have some experience in app development through Java and would love to work on this issue.
I have tried some transitions for the same and have sent the videos on padawan wallet twitter dm. Please assess them and suggest further changes.

**Comment by Prakhar-Agarwal-byte** [comment]
@thunderbiscuit How would u like the transition to be? Can you please share your ideas. I will implement it.
