### ISSUE TITLE
Make link to privacy policy in about section clickable

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [thunderbiscuit/padawan-wallet#239]
The link to privacy policy in "About Padawan" is not clickable. We can make it clickable so when user clicks on the link he will be redirected to the webpage.

**Screenshot:**
![WhatsApp Image 2023-02-28 at 11 37 26 PM](https://user-images.githubusercontent.com/17739006/221943193-1d24a0c3-a740-43e5-8b24-e4012d8ca6e8.jpeg)

**Comment by thunderbiscuit** [comment]
Great idea!
