### ISSUE TITLE
Add a toast on copying Padawan address

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [thunderbiscuit/padawan-wallet#241]
We can add a toast saying address copied when the user clicks on Padawan address in send coins back to us section. This will give feedback to user that the address was copied successfully. 

**Screenshot:**
![WhatsApp Image 2023-03-01 at 1 46 04 AM](https://user-images.githubusercontent.com/17739006/221968530-6f161f76-3dd7-4e94-82ee-43af53291ce9.jpeg)

**Comment by PK284** [comment]
**Can I be assigned to this?**

**Comment by Prakhar-Agarwal-byte** [comment]
@PK284 As u can see, I have already created a PR fixing this issue.
