### ISSUE TITLE
Overridding the text and Step number

### ISSUE THREAD

**Issue by ConnectBhawna** [thunderbiscuit/padawan-wallet#243]
- Under the Learn about Padawan wallet. In the section 1 and section 2 the text is overridding with the tasks.
- I am looking to work on this issue :)
@thunderbiscuit Sir can you please assign this to me. Would love to work on this issue :) 
![issue](https://user-images.githubusercontent.com/81790585/222195864-2c21a3e3-c4b8-44b6-b851-096aa6aa3674.jpg)

**Comment by thunderbiscuit** [comment]
Sounds good! This issue is all yours.

**Comment by ConnectBhawna** [comment]
Thanks @thunderbiscuit sir, I will make the PR :)

**Comment by thunderbiscuit** [comment]
Fixed!
