### ISSUE TITLE
Match the current fragment with correct highlighted tab

### ISSUE THREAD

**Issue by Tanushree-coder** [thunderbiscuit/padawan-wallet#246]
- Upon pressing the back button, the wallet tab shows up but the highlighted tab remains the previous one only.

![WhatsApp Image 2023-03-01 at 15 52 49](https://user-images.githubusercontent.com/75807670/222210352-3a09c39d-f635-4c25-a80e-1057164f65fe.jpeg)

I would love to solve this issue. @thunderbiscuit sir, can you please assign this to me?

**Comment by Tanushree-coder** [comment]
I'll try to fix this soon.

**Comment by Prakhar-Agarwal-byte** [comment]
This issue was resolved via #259 and can be closed now.
