### ISSUE TITLE
Sliding transition playing on pressing bottom tab

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [thunderbiscuit/padawan-wallet#247]
The sliding transition plays even if the user is present on the same screen and presses the same tab. It happens on all the 3 screens. This shouldn't happen and needs to be fixed.

**Video:**

https://user-images.githubusercontent.com/17739006/222235735-4cde62d3-81b3-44f7-82e1-8049d6c32eb1.mp4

**Comment by thunderbiscuit** [comment]
Awesome. Thanks for the hard work!

**Comment by Prakhar-Agarwal-byte** [comment]
This issue is fixed by #249
