### ISSUE TITLE
Content missing in some chapters

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [thunderbiscuit/padawan-wallet#248]
Content is missing in some chapters which should be present in boxes. Is there content already present that we can add here?

**Screenshots:**

 
![WhatsApp Image 2023-03-02 at 12 31 39 AM](https://user-images.githubusercontent.com/17739006/222239944-bc57c73e-a19b-458b-bd5d-a44ffcadb353.jpeg)
![WhatsApp Image 2023-03-02 at 12 31 39 AM (1)](https://user-images.githubusercontent.com/17739006/222239955-281af73e-e0f0-47e0-918e-45fcf693e7ab.jpeg)
![WhatsApp Image 2023-03-02 at 12 31 39 AM (2)](https://user-images.githubusercontent.com/17739006/222239961-5371d763-3c45-4108-a4a9-68a604b5bdbe.jpeg)
![WhatsApp Image 2023-03-02 at 12 31 39 AM (3)](https://user-images.githubusercontent.com/17739006/222239965-468b2226-0f98-4baa-bfe8-5034a78f84f9.jpeg)
![WhatsApp Image 2023-03-02 at 12 31 40 AM](https://user-images.githubusercontent.com/17739006/222239967-96b54a77-e7ce-42ab-8c9b-01fb1f83ad98.jpeg)
![WhatsApp Image 2023-03-02 at 12 28 09 AM](https://user-images.githubusercontent.com/17739006/222239970-29152dbd-bfcb-4a65-a3d5-e68c6a45f13c.jpeg)

**Comment by darkvoid32** [comment]
These content boxes are currently reserved for future GIFS and diagrams!

**Comment by Prakhar-Agarwal-byte** [comment]
I see. Please let me know if I can help with these.👍

**Comment by thunderbiscuit** [comment]
Yeah I'm looking to see if I can convince a graphic designer to help us out and produce diagrams and images for us... stay tuned!

**Comment by ConnectBhawna** [comment]
Hey @Prakhar-Agarwal-byte I can help you out in this case. Let me know what type of design you want for putting here.
I can do designing as well as coding. Good in both :)

**Comment by thunderbiscuit** [comment]
I will close this in favour of #313.
