### ISSUE TITLE
Testnet faucet link not working

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [thunderbiscuit/padawan-wallet#250]
The testnet faucet link mentioned in [Readme](https://github.com/thunderbiscuit/padawan-wallet#where-can-i-get-testnet-coins) is not working https://testnet-faucet.mempool.co/. Do we have an alternative to this faucet or a new link? If there is one we should update it.

**Comment by thunderbiscuit** [comment]
Yep let's update those. Here are two new ones:
1. https://coinfaucet.eu/en/btc-testnet/
2. https://bitcoinfaucet.uo1.net/

**Comment by Prakhar-Agarwal-byte** [comment]
We can close this now
