### ISSUE TITLE
Add spinning sync icon to show status

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [thunderbiscuit/padawan-wallet#252]
We can add a spinning sync icon in the sync button to show that the process is under progress. At present, the user cannot know whether the sync was complete or it's in progress.

**Screenshot:**

![WhatsApp Image 2023-03-03 at 10 49 15 PM](https://user-images.githubusercontent.com/17739006/222785952-9c70ecc7-2269-4a7a-bb2b-15a702f3a278.jpeg)

**Comment by ConnectBhawna** [comment]
Yeah great point ,May i take this and work on this issue?

**Comment by Prakhar-Agarwal-byte** [comment]
@ConnectBhawna Sorry, I forgot to mention I was working on this issue. My PR is almost ready. 😀
