### ISSUE TITLE
Add feedback when users reset completed chapters.

### ISSUE THREAD

**Issue by thetimileyin** [thunderbiscuit/padawan-wallet#256]
At present when users reset completed chapters, they can’t tell if the chapters have truly been reset since there is no feedback or  reaction for the action taken so they keep tapping and tapping till they go back to the 'Learn' tab and see that the chapters have actually been reset. We could add a flash message (pop-up) to let users know that their action has been reacted to. This will help improve user experience on the app.

**Screenshot:**![WhatsApp Image 2023-03-06 at 10 32 03](https://user-images.githubusercontent.com/105345830/223120538-943fd40c-855a-4493-9380-ed18b07876a9.jpeg)

**Comment by thetimileyin** [comment]
I actually worked out a solution for this on the design part
![Padawan](https://user-images.githubusercontent.com/105345830/223121009-0cc1e0a4-d487-45c9-83c2-28746c2b3f14.png)
Here is also a link to the prototype: https://www.figma.com/proto/nCbd7WyTtWsd4GxtLu1vQC/Untitled?node-id=1%3A23&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A23

**Comment by Prakhar-Agarwal-byte** [comment]
I have done a similar work in https://github.com/thunderbiscuit/padawan-wallet/pull/242. I can take this up also.
