### ISSUE TITLE
Use an accepted standard for displaying amounts

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#257]
I think a good place to look for this is the Bitcoin Design Guide. I'm also a fan of the second link proposal.

1. https://bitcoin.design/guide/designing-products/units-and-symbols/
2. https://medium.com/@mark.nugent.iv/grouping-bitcoins-fractional-digits-an-idea-whose-time-has-come-22d9dad8ac51

**Comment by Prakhar-Agarwal-byte** [comment]
I am going through these resources and would like to implement this UI.
