### ISSUE TITLE
Change the icon and text state of the copy _inline_content in Send coins back.

### ISSUE THREAD

**Issue by vickyrules** [thunderbiscuit/padawan-wallet#262]
<img width = "250px" src = "https://user-images.githubusercontent.com/73611313/223704071-becec96d-463c-4fe9-a702-1cb32d2d6fbe.jpg"/>

Currently, the icon and text remain the same even after copying the key.
Want to change the text from "copy" to "copied'  and present  icon with a check icon and then reset to the default text and icon  for few seconds.

for example: 

https://user-images.githubusercontent.com/73611313/223705720-5ccaaf04-6c53-46d1-aa79-8a007bdfe1bb.mp4

**Comment by vickyrules** [comment]
@thunderbiscuit ,if you found the issue relevant, then please assign it. I would love to contribute.

**Comment by thetimileyin** [comment]
Yeah, I think this makes sense

**Comment by vickyrules** [comment]
> Yeah, I think this makes sense

Okay , please assign me this issue.
