### ISSUE TITLE
Making it easier for users to copy their bitcoin address

### ISSUE THREAD

**Issue by Noyi-24-7** [thunderbiscuit/padawan-wallet#265]
As of now when users want to receive bitcoin and want to copy their bitcoin address, it is bit confusing as to how to do that, or if you already know, it is a lot of steps, which include highlighting the address first then using the native copy button. Which is pretty difficult for users it seems.

https://user-images.githubusercontent.com/124662255/224052780-ba31a044-b693-4151-9868-fd56a9f1e371.mp4

**My Propsed Solution**
Provide a dedicated button for users since the main goal is copy or scan, that should be made prominent, so once users click it, the address is directly copied into the clipboard. We could also add extra information so the users know about a little bit about what's happening when they receive bitcoin under the QR Code.

https://user-images.githubusercontent.com/124662255/224053920-2aaedcc4-ac29-45d7-9207-0cbe4ecd95fd.mp4

**Userflow**
<img width="1440" alt="Image" src="https://user-images.githubusercontent.com/124662255/224054856-991d2810-11df-400f-9530-ed58799e2071.png">

Here's a link to the prototype: https://www.figma.com/proto/Ji3dgcP6rzEojrt520nwLc/Padawan-Wallet-Solution-Ideas?page-id=84%3A2832&node-id=84-2846&viewport=242%2C615%2C1.1&scaling=scale-down&starting-point-node-id=84%3A2846

**Comment by Prakhar-Agarwal-byte** [comment]
I can take this up

**Comment by Noyi-24-7** [comment]
That's awesome, if you run into any problems with the design, just lemmi know 👍

**Comment by tajbaba999** [comment]
Hey, @Prakhar-Agarwal-byte are you working on this issue?
I saw that you are working on so many issues and you got assigned to so many issues can I know which issues you are currently working on if you are not working I am ready to take this issue.

**Comment by thunderbiscuit** [comment]
I love your design @Noyi-24-7! Really neat work. Thanks for helping us engineers out!

**Comment by Noyi-24-7** [comment]
> I love your design @Noyi-24-7! Really neat work. Thanks for helping us engineers out!

Sure thing, glad to be of help

**Comment by thunderbiscuit** [comment]
Implemented with 52674892c7d10b65ce5b7dd4e4aa04249515918f! Not as pretty as the design showed here but at least it's a one press copy. Will keep the design here in mind for future development!
