### ISSUE TITLE
Making Transaction Speed/Fees Clearer

### ISSUE THREAD

**Issue by Noyi-24-7** [thunderbiscuit/padawan-wallet#266]
Noticed some people using it don't know what the “fees” part on the sending bitcoin page is used for whether it affects the speed of sending (like how hard it would work to send bitcoin quickly). Essentially they find it difficult to understand that part

<img width="360" alt="Screenshot" src="https://user-images.githubusercontent.com/124662255/224089449-9e7d36ec-9082-4d20-9bc7-30f1b8dadd16.png">

**Solutions**
1st - we could change the copy used there from "Fees (sats/vbytes)" to (Transaction Speed)

2nd - Maybe rather than giving the users too much power? something like that, maybe we can just give them a drop down with 3 options of:
Slow --- Low fees.
Normal --- Medium fees.
Fast --- Large fees.

https://user-images.githubusercontent.com/124662255/224093137-87ddaff2-ad96-46e1-b505-0d3ebc52a6fe.mp4

<img width="1440" alt="Image2" src="https://user-images.githubusercontent.com/124662255/224096682-2a87469c-7ef4-4df6-abcf-f40a4179a26e.png">

I think this could make it easier for users to make proper decisions

Prototype Link - https://www.figma.com/proto/Ji3dgcP6rzEojrt520nwLc/Padawan-Wallet-Solution-Ideas?page-id=84%3A3153&node-id=84%3A3190&viewport=-432%2C341%2C0.59&scaling=scale-down&starting-point-node-id=98%3A5227

**Comment by Prakhar-Agarwal-byte** [comment]
I believe https://github.com/thunderbiscuit/padawan-wallet/issues/221 is related. The second option will make it beginner-friendly as users won't have to use the slider to select the fees rather they can just choose from the 3 options provided.

**Comment by Noyi-24-7** [comment]
> I believe #221 is related. The second option will make it beginner-friendly as users won't have to use the slider to select the fees rather they can just choose from the 3 options provided.

Ohh, I see...but yes I also think it would be easier for users if they know what it would be used for as well as having them understand what each option would mean when sending

**Comment by Prakhar-Agarwal-byte** [comment]
I will create a PR for this 👍

**Comment by Noyi-24-7** [comment]
Ohh, I understand now, testnet has some limitations, if that's the case what if we make that slider into the list the users can select, because as a slider some users don't get enough context as to what is going on with the fees, or we might just include an info tag somewhere to clarify, depends on what's feasible right now tho.

**Comment by darkvoid32** [comment]
I think having what @Noyi-24-7 suggested might be a good solution too, in that we still have the slider, but there is also a tag somewhere to show the user when the sats/vbyte is considered "slow", "medium", or "fast". 
We can temporarily have some hardcoded values, and the technicalities of how we decide what specific sats/vbyte is considered "slow", "medium" or "fast" can be considered later I think!
