### ISSUE TITLE
Add feedback when user carry out transaction

### ISSUE THREAD

**Issue by thetimileyin** [thunderbiscuit/padawan-wallet#267]
When users carry out a testnet transaction, there’s no feedback to let them know if their transaction went through or not unlike other Bitcoin wallets. 
 
![WhatsApp Image 2023-03-08 at 19 14 22 (3)](https://user-images.githubusercontent.com/105345830/224107566-02b19215-4d51-49da-a39e-179fc483c510.jpeg)

**Proposed Solution**
We could add a feedback ( snackbar that shows the transaction is processing just like we did for 'Reset Completed Chapters')
Here is what it should look like:
![Padawan 1](https://user-images.githubusercontent.com/105345830/224108838-1fe32fc0-b67a-488d-bd22-3e691733c982.png)
Figma prototype link (Flow 2): https://www.figma.com/proto/nCbd7WyTtWsd4GxtLu1vQC/Padawan?node-id=47%3A347&scaling=scale-down&page-id=0%3A1&starting-point-node-id=23%3A232

**Comment by Prakhar-Agarwal-byte** [comment]
Nice idea! I will get this going.
