### ISSUE TITLE
Fix navigation in learning and overriding text

### ISSUE THREAD

**Issue by amar683** [thunderbiscuit/padawan-wallet#271]
In the learning section, I notice two things
1) The text is overlaping over the task.
![WhatsApp Image 2023-03-20 at 18 16 03](https://user-images.githubusercontent.com/69433283/226347691-2c2948d5-ebc4-4aea-b33e-a921df0234c5.jpg)
2) After completing a chapter, the default chapter is always the first one, when we open the app and if we completed a chapter it stays on that chapter and button text also stays the same "Start chapter", while it should be pointed out to another chapter that need to be open.
![WhatsApp Image 2023-03-20 at 18 25 24](https://user-images.githubusercontent.com/69433283/226348810-d185d3bb-261d-4fb8-b35d-4ac68be304a4.jpg)
![WhatsApp Image 2023-03-20 at 18 42 40](https://user-images.githubusercontent.com/69433283/226349108-88b0bc44-8ebc-46c6-ac80-54f25ac9c10d.jpg)
Solutions :
for the first one instead of a text we should do like progress bar for every section, which shows how much the progress in perecentage, and whatever chapter is done instead of "Start chapter, we can write "Restart Chapter", which will be more convenient to user.
After completing one chapter it should directly point to next chapter or section.
![Untitled (1)](https://user-images.githubusercontent.com/69433283/226368798-bbd4fc7f-4f33-42ca-9e95-0903df8aaa21.jpg)
@thunderbiscuit Sir can you please assign this to me. Would love to work on this issue specially on the navigation one.

**Comment by thunderbiscuit** [comment]
I think this issue outlines 3 different things.

1. For the padding issue and the overlap on small screens, this is being dealt with in PR #253. Feel free to review that and comment there if you think it could be improved!

2. The change from "1 of 3" to a percentage is aesthetic only, and I'm not sure it adds much yet. It's something we could ask a designer about, but I'm not in a rush to make that change.

3. Restart chapter is sort of the same. I'm not _against_ the idea, but I don't know if it adds enough to be worth the change. Let me sit on it for a day or two, but I would say don't put too much effort into it just yet.
