### ISSUE TITLE
Sync button should touch the edge of the balance card

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#272]
The sync button has a slight distance between itself and the card containing it, and I think it would clean it up to have it completely against it. See the very small blue line below the button.

![image](https://user-images.githubusercontent.com/39974688/226928290-6e990c77-3909-494d-948d-95f14358aa7a.png)

**Comment by Prakhar-Agarwal-byte** [comment]
Yes, it should touch the edge of the container.

**Comment by vickyrules** [comment]
@thunderbiscuit I'm working on an issue related to the sync button #273, if it is fine, I would be glad to take this
