### ISSUE TITLE
Sync button icon animation

### ISSUE THREAD

**Issue by vickyrules** [thunderbiscuit/padawan-wallet#273]
currently, the sync button remains the same when the user clicks on sync.
Animate the icon when the button clicks and stop when sync is success it stops.

**Comment by Prakhar-Agarwal-byte** [comment]
This issue is already raised https://github.com/thunderbiscuit/padawan-wallet/issues/252 and I have raised a PR for it  https://github.com/thunderbiscuit/padawan-wallet/pull/254
