### ISSUE TITLE
Sync button rotates backwards forever if clicked repeatedly quickly

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#276]
I don't know that this is happening on all devices, but I can definitely reproduce on mine and on the emulator.

**Comment by Ayan-10** [comment]
Hi @thunderbiscuit, I can't reproduce the issue on my device. 

Tested beta on Realme GT Master with API level 33.

**Comment by thunderbiscuit** [comment]
I have changed the rotating icon for a cooler loading indicator! Not a bug anymore.
