### ISSUE TITLE
UnsatisfiedLinkError while creating wallet

### ISSUE THREAD

**Issue by Ayan-10** [thunderbiscuit/padawan-wallet#277]
Got UnsatisfiedLinkError after clicking the `create wallet` button.

**Screenshot:**
<img src="https://user-images.githubusercontent.com/71203077/227701182-d64e7f6b-fe68-40e4-b997-f47172003aa3.png" width=300/>

**Logs:**
```
2023-03-25 12:03:01.779 24416-24416 PadawanActivity         com.goldenraven.padawanwallet.debug  I  Could not build wallet: java.lang.UnsatisfiedLinkError: Unable to load library 'bdkffi':
                                                                                                    dlopen failed: library "libbdkffi.so" not found
                                                                                                    dlopen failed: library "libbdkffi.so" not found
                                                                                                    dlopen failed: library "libbdkffi.so" not found
                                                                                                    Native library (android-x86/libbdkffi.so) not found in resource path (.)

```

Tested beta on Pixel 3 emulator with API level 30.

**Comment by thunderbiscuit** [comment]
Hey! thanks for testing out the app. 

What is happening most likely is that you're running a 32-bit emulator (x86) instead of a 64-bit emulator (x86_64), and we don't support 32-bit architectures in the bitcoin dev kit language bindings library. I do not know why this is the default emulator downloads for a lot of Android Studio versions, but you'll likely fix your bug by downloading an x86_64 emulator in Android Studio.

Let me know if that doesn't solve your issue!

**Comment by Ayan-10** [comment]
@thunderbiscuit Thanks for the information, it solves the issue. 

Also, I was thinking to make a proposal for the padawan wallet in the Summer of Bitcoin, and I am exploring the issues to contribute here and to get familiar with the codebase. Can you elaborate a little on this year's Summer of BItcoin project idea which is **Advanced bitcoin features on Padawan Wallet**, like what are the expected outcomes and some features that we have to work on? It will help me to understand the project idea more accurately.

**Comment by thunderbiscuit** [comment]
Your best bet is to download the app and start playing with it. I think you'll find all sorts of little bugs. Feel free to open issues and if they're worth tackling you can also make PRs!

The app is in a state where we need to polish up some stuff, get a designer to build images/diagrams for us, and release a 1.0 version! Related are the [Devkit Wallet](https://github.com/thunderbiscuit/devkit-wallet) and [Tatooine faucet](https://github.com/thunderbiscuit/tatooine). Proposals to explore/add to all 3 of these projects will be considered.
