### ISSUE TITLE
QR image generating taking too long

### ISSUE THREAD

**Issue by yellowHatpro** [thunderbiscuit/padawan-wallet#278]
- IMO, The QR generation is happening on the main thread. Therefore it's too slow. Because of it, clicking on the Recieve button seems buggy, as visible in the recording:

https://user-images.githubusercontent.com/75999921/227734897-f0d64df6-f780-4a19-9c47-15ccb7dc674d.mp4

Fixes: 
- We can switch the context using `withContext(Dispatchers.IO)` and call the corresponding qr generation function there.
- Visible changes: 

 https://user-images.githubusercontent.com/75999921/227734881-3e8149fd-fd58-4f68-b866-c998a310e22c.mp4

**Comment by yellowHatpro** [comment]
@thunderbiscuit is the issue there on other devices??
Can you confirm if it persists in your device/emulator?

**Comment by thunderbiscuit** [comment]
Yes I think there are a few things at play here. This is a good place to discuss maybe what's wrong with this screen.

One of the issues with that screen (I have not deeply investigated this yet) is that it tends to trigger a lot of recompositions of the composables. I'm not sure why.

In theory, the main thread at that point does nothing else than get this address from the wallet. I don't know that sending this work to a background thread should "speed it up" per se. I'm also not sure _which_ part is actually the slowest part of this process. Is it the call to the Wallet object? Or the `addressToQR()` function? We could potentially pre-compute these things on a background thread as the user opens the screen and have it ready for them before they even click the button, which would then make it seem like the process was really fast. But even that feels a bit like over-optimization to me at the moment. Any thoughts on that?

On my devices and emulators it's not very slow to load this address (as opposed to navigating to the screen itself, which tends to be a bit slow I find).

**Comment by yellowHatpro** [comment]
I think generating the address is not a problem, but generating an image without thread switching will block the main thread. So what I am doing is, that I am calling the `addressToQR()` function within a LaunchedEffect, which depends on the address itself, so the image generation is now bound to the address, which I don't think changes frequently or on its own.

**Comment by yellowHatpro** [comment]
I will try to check if there are other recompositions in the mentioned screen, but I suppose generating the QR in the background should be a safe call. Although, it might be noticeable to me because my device is a slow potato ＞﹏＜.

**Comment by yellowHatpro** [comment]
Yeah slow won't be an appropriate word here. I was referring to the delay it causes.
