### ISSUE TITLE
Send Screen Directly returns to Wallet Screen After clicking on camera

### ISSUE THREAD

**Issue by Ayan-10** [thunderbiscuit/padawan-wallet#280]
On the send screen after clicking on the camera icon, the app sometimes directly sends the user to the wallet screen. After detecting the QR the app should stay on the send screen. 

**Screencast:**

https://user-images.githubusercontent.com/71203077/227799430-209e31b6-89f3-402d-9577-83b9ae6aca31.mp4

**Comment by thunderbiscuit** [comment]
Yes! I don't know why this happens. If you want to investigate that, go for it.

**Comment by Prakhar-Agarwal-byte** [comment]
@Ayan-10 Are you still working on this?

**Comment by Ayan-10** [comment]
Yes @Prakhar-Agarwal-byte

**Comment by thunderbiscuit** [comment]
Fixed with 2bd09a603f8445e9d8f70474514fc2a973c08802.
