### ISSUE TITLE
Verify transaction button not visible properly on 2nd send 

### ISSUE THREAD

**Issue by netavya2003** [thunderbiscuit/padawan-wallet#281]
**The first send works fine like it is supposed to** 

![idle](https://user-images.githubusercontent.com/111112186/228136107-172acc31-96d9-4461-a280-81260fdcfff6.jpeg)

 **on the second send , if we don't restart the application the verify transaction button is not visible properly**

![2nd transaction](https://user-images.githubusercontent.com/111112186/228136238-a8f37fac-bf6d-4e6e-a248-b6e7a240ee65.jpeg)

 this error  was founded in Android version 13 , device model RMX3031

**Comment by thunderbiscuit** [comment]
Thanks for reporting this! I think it's related to how we handle smaller screen sizes. Note how your balance in the second screenshot takes up two lines.

See #282

**Comment by thunderbiscuit** [comment]
Will close this in favour of #282, where we'll keep a long-running list of issues related to small screen size.
