### ISSUE TITLE
Bottom navigation bar is not working properly

### ISSUE THREAD

**Issue by guptasandeep7** [thunderbiscuit/padawan-wallet#285]
When you click the Learn icon and then press the Back button, you will be taken to the Wallet screen, but the navigation bar still highlights Learn icon.

![nav bar issue](https://user-images.githubusercontent.com/76438283/229362687-ce82b63b-9b0f-49e6-a103-09c522990c3c.png)

**Comment by thunderbiscuit** [comment]
Hi there! I think you might not be building the app from the latest master branch (or maybe you're using the app downloaded from the Play Store). This is a nice little bug, and it was solved in #259!

If you try building the latest version you'll find it all fixed. Cheers!

**Comment by guptasandeep7** [comment]
Thanks, @thunderbiscuit
