### ISSUE TITLE
Bug: Double click on receive or send button opens fragment multiple times 

### ISSUE THREAD

**Issue by guptasandeep7** [thunderbiscuit/padawan-wallet#287]
When we double-click the receive button, it opens the receive fragment twice, and just like with the send button, we must repeatedly hit the back button to close it. 

https://user-images.githubusercontent.com/76438283/229514152-dce8224f-4430-4819-9b69-c10c1e1cd7ce.mp4

@thunderbiscuit  I can resolve this issue please assign it to me.

**Comment by thunderbiscuit** [comment]
Yep this is definitely a bug. Feel free to take this up. Also just FYI, I'm the lead maintainer of this repo, so I get notifications for all messages/issues/PRs. You don't need to tag me in threads 😆.
