### ISSUE TITLE
Feature: Add share button in receive fragment

### ISSUE THREAD

**Issue by guptasandeep7** [thunderbiscuit/padawan-wallet#288]
In receive fragment, we can add share button so user can share their wallet address to others via message or any social media like (WhatsApp).

Below image is only for explanation. Please ignore the design ( I am not a UI/UX developer ).

![share button](https://user-images.githubusercontent.com/76438283/229532804-48802348-3955-4752-a5a8-e0703979effc.png)

**Comment by thunderbiscuit** [comment]
I'm not opposed to this idea. Connected to #265.

**Comment by Noyi-24-7** [comment]
Hmmmm, I like the idea, I'll try and whip up a flow and some designs 👍

**Comment by amritakesh** [comment]
![WhatsApp Image 2023-04-05 at 21 45 23](https://user-images.githubusercontent.com/74363370/230142377-a50f1f0b-85c4-43da-83bd-b28bba99e341.jpeg)

why dont we add a copy option like here too?
