### ISSUE TITLE
Get coins button leads to ANR

### ISSUE THREAD

**Issue by amritakesh** [thunderbiscuit/padawan-wallet#290]
Everytime get coins button is selected the app stops responding. Sometimes the screen freezes , other times the app randomly shuts

**Comment by thunderbiscuit** [comment]
@nerd2ninja nope the binaries you can download on GitHub are fully functional!

**Comment by thunderbiscuit** [comment]
Closing this issue now as it's not actually a bug per se, but I'm glad we have it now in the archive for people who might search for this issue in the future!
