### ISSUE TITLE
Adding a progress bar to Learn segment

### ISSUE THREAD

**Issue by amritakesh** [thunderbiscuit/padawan-wallet#291]
As padawan is for beginners , adding a progress bar in the learn section can help new users track their learning. For now the learn section has less content, but as the app grows and new chapters are added, a progress bar can help the users in understanding their progress.

**Comment by thunderbiscuit** [comment]
Let us know what you have in mind. There is already a small "progress bar" for each of the sections, so do you have something else in mind? Feel free to share designs/screenshots if you'd like.

**Comment by thunderbiscuit** [comment]
I will close this issue for now as it is not very active. Feel free to reopen if you want to work on it!
