### ISSUE TITLE
Make the "Finish" button of the same size in chapters

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [thunderbiscuit/padawan-wallet#296]
The `Finish` button here is smaller than the `Prev` and `Next` buttons. 

![WhatsApp Image 2023-04-08 at 2 40 27 PM](https://user-images.githubusercontent.com/17739006/230713587-c8d116dc-91ec-44aa-bf40-b97be3cb84e6.jpeg)

We should make it the same size as the other buttons.

**Comment by Prakhar-Agarwal-byte** [comment]
I think the difference in size is due to the icons in Prev and Next buttons. I will add some padding in the Finish button to fix this.

**Comment by thunderbiscuit** [comment]
Yes something about the way the weight is distributed between the two buttons I think might be the cause. Somehow the "Prev" button keeps the same size across devices and the other button always just uses whatever space is left (not sure about this, just a feeling).

**Comment by thunderbiscuit** [comment]
On my emulator it looks like this is not yet fixed. The buttons are closer in size, but not identical by default (and I don't think they're the same length).

I think the issue is that the fix in #300 is hard-coding a padding value, but that won't really fix the issue on all screen sizes.

**Comment by darkvoid32** [comment]
My bad, totally forgot about padding potentially being different for all screen sizes.
