### ISSUE TITLE
Highlight the Bottom Navigation Tab

### ISSUE THREAD

**Issue by Prakhar-Agarwal-byte** [thunderbiscuit/padawan-wallet#297]
The `Wallet`, `Learn` and `Menu` bottom navigation tab gets deselected when any screen inside of it is opened. The correct tab should remain selected.

![Add a little bit of body text](https://user-images.githubusercontent.com/17739006/230714365-a71bbbcd-9573-4f3c-9ad0-f2823978ea47.png)

**Comment by Prakhar-Agarwal-byte** [comment]
I will start working on it

**Comment by thunderbiscuit** [comment]
Yeah good catch.

**Comment by thunderbiscuit** [comment]
Fixed with 0a0e0fd243331d50e4d3ad23e44e346de330be98.
