### ISSUE TITLE
Feature: Option for choosing an image from gallery in QR Screen

### ISSUE THREAD

**Issue by Ayan-10** [thunderbiscuit/padawan-wallet#299]
In the current version of the app, QR can be scanned using the camera. There should be an option to choose an image from the gallery so that users can scan QR codes from an image or screenshot.

**Comment by thunderbiscuit** [comment]
Mmmm yes this might be interesting. I'll need to think on it a bit. Let me flag this for a potential 2.0 version of the app.

**Comment by darkvoid32** [comment]
This would be a convenient way for people to pass QRs to one another through text, which will parallel other online banking payment methods.

I think it would be a good 2.0 feature!
