### ISSUE TITLE
Generating an address displays a different string for a moment

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#301]
I _think_ this is a small snag introduced in #278.

The QR image displays the string "No address yet" for a split second while the actual first address is computed.

https://user-images.githubusercontent.com/39974688/231176470-ff084bf3-c20f-4acb-8987-f27da82c0b6d.mov

**Comment by yellowHatpro** [comment]
I am sorry but I didn't get the issue. Can you elaborate on how we know where is the "No address yet" displayed?

**Comment by yellowHatpro** [comment]
DId you mean the QR that was visible for a split second, when scanned, gives "No address yet" ?
