### ISSUE TITLE
Fix chapter 7

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#328]
Let's update the recommendations for where and how to store a recovery phrase. We can use this issue to discuss the phrasing.

@DrJonesKlaus you had some ideas?

**Comment by DrJonesKlaus** [comment]
At the end of the second page of the chapter 7, where it is mentioned that:

> "...is generally a good practice to write down this recovery phrase on physical objects like paper or metal (not saved on a computer)"

Just in case someone not very technical or privacy focused decides to learn using Padawan, I think it might be a good idea to add:

"...(not saved on any electronic device such as computers, mobile phones or pictures )"

**Comment by thunderbiscuit** [comment]
Good idea. I'll add it in the next release.

**Comment by Shivoham102** [comment]
Hello, I am new here. I would like to solve this issue. Can I be assigned this issue?

**Comment by thunderbiscuit** [comment]
This is not tracked in #365. Closing now.
