### ISSUE TITLE
Navigation bar colour is not set to match colour theme

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#33]

**Comment by thunderbiscuit** [comment]
This is what it looks like:

![bug](https://user-images.githubusercontent.com/39974688/152881330-052201e4-3a54-40d7-b261-22dd0a1e14c0.png)

**Comment by iipranavii** [comment]
The buttons now look more prominent in my opinion.

![image](https://user-images.githubusercontent.com/67915580/159963519-b5e3a69c-1d3a-4ab6-bfa7-c0b2eab8c1e3.png)


Button Colour: EBDBB2
Text Colour: 32302F
(followed the gruvbox theme)

**Comment by thunderbiscuit** [comment]
@iipranavii I think it might be interesting to change the colours on the buttons for sure, but this issue is not quite about that so I don't want to confuse the two into the same discussion. Feel free to open an issue for the colours if you'd like!

**Comment by DolUnity** [comment]
@thunderbiscuit if you can tell me what colour the navigation bar should have I would take a look into it in the next few days.

**Comment by thunderbiscuit** [comment]
Thanks for offering! But actually I'm re-writing the whole UI in Jetpack Compose at the moment (the intro screens have been updated and I'm now working on the wallet/tutorials), so this issue will not be relevant anymore. It _might_ be that we need to open a new issue for something similar, but I'm not sure. But this particular issue/screen doesn't exist anymore, so I'll close. Cheers!
