### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by qxotk** [thunderbiscuit/padawan-wallet#345]
I am opeing an issue to explore providing a Spanish language version of the app and educatuonal materials.

Here is my background:

I evangelize Bitcoin use locally to people nearby.  I encounter enough people speaking Spanish as their native tongue and English is sometimes a limiting factor.

I have never added a localization layer from scratch before, nor have I ever participated in a localization effort.

I have many years programming experience and I understand the basic concepts of localization of resources, some Java and some Android programming experience and basic understanding of functional prigramming.

**Comment by qxotk** [comment]
Just read release notes of latest release - Spanish version already done.

**Comment by qxotk** [comment]
Tried to close - app already has a Spanish translation.

**Comment by thunderbiscuit** [comment]
Hey thanks for looking into contributing! I do indeed have Spanish localization already (thank you @DrJonesKlaus!) but one thing you can do for sure is to take a look and let us know if it's all there, and if all the language is clear (Spanish is spoken around the world so it's always good to hear from different people if the wording makes sense for them).

Cheers!
