### ISSUE TITLE
Suggestion:Introducing a dummy trading scenario for users to practice

### ISSUE THREAD

**Issue by Ashurajput02** [thunderbiscuit/padawan-wallet#354]
The app provides users with insights into bitcoins, covering topics such as sending, receiving, recovery, etc. However, a significant number of users interested in learning about bitcoins are attracted by its increasing popularity in the trading sector. After the basic sessions, we should consider guiding them on how to trade bitcoins on the testnet. This could be in the form of a tutorial, similar to the experience of playing a game for the first time, where users are introduced to basics, hurdles, how to manage them, and basic controls.

**Comment by darkvoid32** [comment]
We currently recommend users that finish the tutorials to trade with their friends, but I think having a dummy trade scenario might be a even better way to help new-comers onboard sending / receiving!

I'm thinking we can guide them along sending / receiving, but it's only a dummy scenario, so no actual sats are used (together with showing problems that might occur and how to solve them).

What do you think?

**Comment by darkvoid32** [comment]
Do send a message to @thunderbiscuit, as he is in charge of the project! He will have a much clearer vision on what you can do or plan to do in the future!

**Comment by Ashurajput02** [comment]
I mailed him earlier.
Let me remind him again.

**Comment by Ashurajput02** [comment]
It would be great if you could share me his discord id or some group id of padawan wallet if any

**Comment by thunderbiscuit** [comment]
Hi guys! Thank you for taking a look at the app and thinking about ways to make it better. Scenarios for learning how to trade bitcoin however, are fairly out of scope for the project, not only because it would be hard to recreate using testnet coins but also because it's not really what I'm after here. Trading is not the core of what makes bitcoin important IMO.
