### ISSUE TITLE
Notice of release of Swift code and app under the Apache 2.0 license

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#356]
Good work has been done towards an iOS app of Padawan. This issue is to track acknowledgement that this work is released under the Apache 2.0 license, same as the Kotlin code written for the Android app.

The following license notice will be added to the top of the Swift files:

```swift
//
// Copyright 2024 thunderbiscuit, geigerzaehler, and contributors.
// Use of this source code is governed by the Apache 2.0 license that can be found in the ./LICENSE file.
//
```

Tagging @geigerzaehler242 for your approval of this license. Cheers!

**Comment by geigerzaehler242** [comment]
approved
