### ISSUE TITLE
Use snackbar instead of toast when copying address on clipboard

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#50]

**Comment by thunderbiscuit** [comment]
Yep still open! So you're not getting a toast on your side? This is a screenshot of what I get when I press "copy address":

<img src="https://user-images.githubusercontent.com/39974688/156384765-6ee52960-8f79-4d00-95eb-4f6e4f768b39.png" width="200" />

**Comment by darkvoid32** [comment]
Nope! The toast does not pop up for me (Google Pixel 4A). I can take this issue, hopefully the issue will resolve itself when changed to using a snackbar.
