### ISSUE TITLE
Add ability to send to multiple addressees

### ISSUE THREAD

**Issue by thunderbiscuit** [thunderbiscuit/padawan-wallet#52]

**Comment by Ayan-10** [comment]
@thunderbiscuit Can I work on this issue?

**Comment by thunderbiscuit** [comment]
It's not currently on my radar for the 1.0 release. In fact I think it might not be useful as much as I initially thought (for a learning app). It either belongs in a separate "advanced features" section of the app (maybe some setting users could turn on when they've completed all chapters), or not really in Padawan entirely. I think I'll close this issue for now, and maybe revisit later if the app ever grows into something we want to offer a second step for.

Thanks for taking an interest in it!
