### ISSUE TITLE
Add build instructions

### ISSUE THREAD

**Issue by emanuelb** [thunderbiscuit/padawan-wallet#85]
Add build instructions to README.MD which is cloning this repo and running `./gradlew assembleRelease` but its failing with:
```
* What went wrong:
Execution failed for task ':app:dataBindingMergeDependencyArtifactsRelease'.
> Could not resolve all files for configuration ':app:releaseCompileClasspath'.
   > Could not find org.bitcoindevkit.bdkjni:bdk-jni-debug:0.2.0.
     Required by:
         project :app
```

How to build the bitcoindevkit dependency? add instructions for it as well.
as tried without it the above on latest tag v0.6.0 with Containerfile.

```dockerfile
FROM frolvlad/alpine-glibc

RUN set -ex; \
    apk update; \
    apk add --no-cache \
        openjdk8 \
        git; \
    adduser -D appuser;

USER appuser

ENV ANDROID_SDK_ROOT="/home/appuser/app/sdk" \
    ANDROID_HOME="/home/appuser/app/sdk"

RUN set -ex; \
    mkdir -p "/home/appuser/app/sdk/licenses" "/home/appuser/app/padawan/"; \
    printf "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "/home/appuser/app/sdk/licenses/android-sdk-license"; \
    cd /home/appuser/app/padawan/; \
    git clone https://github.com/thunderbiscuit/padawan-wallet; \
    cd padawan-wallet; \
    git checkout v0.6.0;
```

**Comment by thunderbiscuit** [comment]
It's a great idea to add a section in the readme on how to build the bitcoindevkit, as well as how to build the app from source.

I'm not too familiar with podman (and only with the basics of Docker) but I'm looking into it. In the meantime if you're looking to add to the Containerfile the steps to build the bitcoindevkit, I can vouch for the [readme on the repo here](https://github.com/bitcoindevkit/bdk-jni) as I've contributed to it. You'd basically only need to add the Rust toolchain and the few commands to build and publish to the localMaven repository.

I'll be looking to add the short version of that to the readme. Thanks for the recommendation!

**Comment by mbcse** [comment]
Will work on this!

**Comment by thunderbiscuit** [comment]
I think this might be fixed now with the migration to `bdk-android` to Maven Central! Let me know if you get around to testing it!
